# Generated by Django 3.2.8 on 2021-10-29 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_auto_20211029_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storequiz',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storequiz', to='quizapp.answerss'),
        ),
    ]
