# Generated by Django 3.2.8 on 2021-10-30 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0004_alter_storequiz_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storequiz',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ansstorequiz', to='quizapp.answerss'),
        ),
    ]
